### ISSUE TITLE
write "Writing persistent objects" topic

### ISSUE THREAD

**Issue by jimfulton** [zopefoundation/zodbdocs#12]

**Comment by jamadden** [comment]
Here's a gotcha on writing persistent objects that took us awhile to figure out.

Suppose you have a persistent object:
```python
class P1(persistent.Persistent):
   def __init__(self):
        self.thing = 0
```

And suppose you have another persistent object that has a reference to this one:
```python
class P2(persistent.Persistent): 
    def __init__(self):
        self.p1 = P1()
```

For its own reasons, `P2` wants to have a property that manipulates the state of its `P1`:
```python
 class P2...:
     p1_thing = property(lambda s: s.p1.thing, lambda s, nv: setattr(s.p1, 'thing', nv))
```

Suppose you have a saved instance of `P2` called `p2`. If you use this property (`p2.p1_thing = 1`) you would expect that `p2` would still be saved and only `p2.p1` would be changed. But instead, you find that *both* objects are changed! Surprise! Happy conflict!

```python
# db = ...; p2 = ...
>>> conn = db.open()
>>> conn.root()['key'] = p2
>>> import transaction
>>> transaction.commit()
>>> p2._p_status
'saved'
>>> p2.p1_thing = 3
>>> p2._p_status
'changed'
>>> p2.p1_thing._p_status
'changed'
```

This bit us when we tried to use the conflict-reducing `zope.minmax` numeric objects as a property. Those objects are persistent, and they have a `value` member. So trying to expose the `value` as the actual property (keeping the fact that it was a `zope.minmax` object an implementation detail) lead to the holding object still being changed, completely defeating the point.

We managed a workaround, but it's ugly. 

It'd be nice to see the fact that setting a property cause the object to be changed, even if the property didn't update the object itself, documented. (Or fixed 😄)

**Comment by jimfulton** [comment]
I'm curious what sort of fix you have in mind. I fear the cure would be worse than the disease.

**Comment by jamadden** [comment]
I'm not sure there's a general, automatic fix that also performs well. The general case would require the `__setattr__` implementation to detect if the attribute name referred to a data descriptor (`type(self).__dict__.get(attr_name) hasattr __set__ and __get__`), then run the normal attribute setting code, and then check to see if the instances `__dict__` or slots have actually been modified, which could be a very expensive thing to do.

Our solution was to make the Persistent subclass (P2) declare which properties were actually not going to be modifying the instance, and we overrode `__setattr__` to call the descriptor directly, bypassing the Persistent machinery altogether:
```python
class PersistentWithProperties(Persistent):
	def __setattr__(self, name, value):
		pers_descriptor = _get_or_make_pers_prop_cache(type(self)).get(name)
		if pers_descriptor is not None:
			pers_descriptor.__set__(self, value)
		else:
			Persistent.__setattr__(self, name, value)
```

The class tells us that a property won't change the instance by making it extend a special base class, for safety, but you could also use string names. We don't look up the descriptor directly in the type but instead we cache a flattened representation of all such descriptors because testing showed it to be faster if the MRO was very deep.

**Comment by jimfulton** [comment]
Thinking about this, IMO, rather than going to this much trouble to implement a property, it would have been better to use a setter method.

**Comment by jamadden** [comment]
Possibly, yes, but we were evolving a *large* codebase that assumed it could write to `lastModified` willy nilly, so a property it had to be. 

It's still a bit of a gotcha, though.
