### ISSUE TITLE
Write "Storages" topic

### ISSUE THREAD

**Issue by jimfulton** [zopefoundation/zodbdocs#14]

**Comment by jamadden** [comment]
I guess RelStorage will get a shout-out here?

**Comment by jimfulton** [comment]
Yes, In fact, I was planning to ask you to write a sub-topic on it.

**Comment by jamadden** [comment]
I'd be happy to!

**Comment by jimfulton** [comment]
This was addressed in the storages section of the references doc.

@jamadden, feel free to update the relstorage blurb, if necessary. http://zodb-docs.readthedocs.io/en/latest/reference/storages.html#noteworthy-non-included-storages

**Comment by jamadden** [comment]
I like the RelStorage blurb, thank you. 

The only thought I had was, given the introductory level of this documentation, is it safe to assume that readers will know what "relational database" means? Especially since "database" is an overloaded term. Perhaps adding an example or two might clarify? "RelStorage stores data in relational databases *like MySQL* or *PostgreSQL*." 

I can't decide if that helps or clutters.

**Comment by jimfulton** [comment]
I don't think it would hurt. I also think that readers are likely to know what relational databases are.
